services:
  postgres:
    image: postgres:latest
    container_name: syllabus
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=SYLLABUS